import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../..");
const outputDir = path.resolve(__dirname, "../netlify/functions/_shared/content");
const bundlePath = path.resolve(__dirname, "../netlify/functions/_shared/content-bundle.ts");

const files = [
  ["prompts/system.md", "prompts/system.md"],
  ["prompts/routing.md", "prompts/routing.md"],
  ["agents/receptionist/agent.md", "agents/receptionist/agent.md"],
  ["agents/sales/agent.md", "agents/sales/agent.md"],
  ["agents/marketing/agent.md", "agents/marketing/agent.md"],
  ["agents/bi/agent.md", "agents/bi/agent.md"],
  ["shared/company.md", "shared/company.md"],
  ["shared/products.md", "shared/products.md"],
  ["shared/pricing.md", "shared/pricing.md"],
  ["shared/faq.md", "shared/faq.md"],
  ["shared/policies.md", "shared/policies.md"],
  ["shared/brand_voice.md", "shared/brand_voice.md"],
  ["shared/sops.md", "shared/sops.md"],
  ["shared/documents.md", "shared/documents.md"],
];

fs.mkdirSync(outputDir, { recursive: true });

const bundle = {};

for (const [source, dest] of files) {
  const sourcePath = path.join(repoRoot, source);
  const destPath = path.join(outputDir, dest);
  const content = fs.readFileSync(sourcePath, "utf8");
  fs.mkdirSync(path.dirname(destPath), { recursive: true });
  fs.copyFileSync(sourcePath, destPath);
  bundle[dest] = content;
}

const bundleSource = `// Auto-generated by scripts/sync-content.mjs — do not edit manually.
export const bundledContent: Record<string, string> = ${JSON.stringify(bundle, null, 2)};
`;

fs.writeFileSync(bundlePath, bundleSource, "utf8");

console.log(`Synced ${files.length} content files to ${outputDir}`);
console.log(`Generated content bundle at ${bundlePath}`);
